use HackerRank_SQL;

--Using WHERE clause
SELECT COUNT(NAME)
FROM CITY
WHERE POPULATION > 100000;

--Using having clause
SELECT SUM(city_count)
FROM(
	SELECT COUNT(NAME) as city_count
	FROM CITY
	GROUP BY POPULATION
	HAVING POPULATION > 100000
	) AS Number_of_City;
